### ISSUE TITLE
UI: Timeline

### ISSUE THREAD

**Issue by DineshKumarVasudevan** [mrc-india-csr/katha-utsav-2021-fe#3]
As an Event Manager
I want to display the timeline of my event in the website
so that the registrants can get an idea about the event's history.

**Acceptance Criteria:**
Given an individual opens the Katha Utsav website
When he/she clicks on the Timeline link
Then the Timeline section with the details present in the UX should be displayed to the individual.

Reference: https://www.figma.com/proto/A3B6c6710hpLvDUNvDrJcc/Katha-Utsav?page-id=0%3A1&node-id=223%3A327&viewport=241%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=1%3A2

Dev Comp: 8/27

Merged with Master, will be pushed to QA - 08/31

**Comment by Magichida** [comment]
Below the Timer,  format should be added in the UI.
[UI_ Timeline.docx](https://github.com/mrc-india-csr/katha-utsav-2021-fe/files/7098249/UI_.Timeline.docx)

**Comment by Magichida** [comment]
Issue is fixed

![image](https://user-images.githubusercontent.com/89193009/131964240-eb2b15ca-ad3a-4972-bbef-93aced833fbb.png)
