### ISSUE TITLE
Create a Gallery

### ISSUE THREAD

**Issue by karthy1104** [mrc-india-csr/katha-utsav-2021-fe#31]
As a user
I want to view the Gallery
So that I can get a feel of the event organized in Previous years

GIVEN I am in the Katha home page
WHEN I am in the Gallery section
THEN I should see the below 
 - Section Title "Previous Years"
 - Static Images (Refer UX)

**Comment by Magichida** [comment]
There should be a proper gap between the photos like figma
[Create a Gallery.docx](https://github.com/mrc-india-csr/katha-utsav-2021-fe/files/7098301/Create.a.Gallery.docx)

**Comment by Magichida** [comment]
Below are update given by Vignesh,

Regarding the spacing, design team is fine with it, we cant get exact spacing because we have to align the photos dynamically for all sizes
