### ISSUE TITLE
UI: Process

### ISSUE THREAD

**Issue by DineshKumarVasudevan** [mrc-india-csr/katha-utsav-2021-fe#4]
As an Event Manager
I want to display the processes involved in the website
so that the registrants can get an idea about the progression of the event.

**Acceptance Criteria:**
Given an individual opens the Katha Utsav website
When he/she clicks on the Process link
Then the Process section should be displayed with all the details present in the UX design.

Reference: https://www.figma.com/proto/A3B6c6710hpLvDUNvDrJcc/Katha-Utsav?page-id=0%3A1&node-id=223%3A327&viewport=241%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=1%3A2

Dev Comp: 8/27

**Comment by Magichida** [comment]
1. Found alignment difference between firefox and chrome
2. Stage 1 upload stories title should be removed in the right hand side
3. Hand Image of one, two and three should be on the left side
4. should have space between the Hand image and stage
5. Font and size should be unique as like UX design
[UI_Process.docx](https://github.com/mrc-india-csr/katha-utsav-2021-fe/files/7098325/UI_Process.docx)
.

**Comment by Magichida** [comment]
**Issue 2,3,4 is fixed.**

Still we have issue 1 ( firefox browser ) and 5 - **yet to be fixed.**
Below is the image of Chrome
![image](https://user-images.githubusercontent.com/89193009/131965140-deabe530-36aa-40b0-8c6d-d0c663054c4b.png)

**Comment by Magichida** [comment]
**issue 1 ( firefox browser ) and 5 - Fixed**

Chrome
 
![image](https://user-images.githubusercontent.com/89193009/131984148-5ab0597e-c0b8-46d5-ab83-d72bda055f32.png)

Firefox
 
![image](https://user-images.githubusercontent.com/89193009/131984154-cd52dc33-4d35-456b-875a-d0bd33abcda2.png)

**Comment by Magichida** [comment]
title is not displaying bold as like in chrome and Firefox " Here's what we're  looking for in the your entries" 

![image](https://user-images.githubusercontent.com/89193009/133217258-88387e8c-5d41-458b-9823-16fc7e269b57.png)

Chrome
![image](https://user-images.githubusercontent.com/89193009/133217433-0bf10cc7-f20b-4897-9c45-7fa40461ebb6.png)
