### ISSUE TITLE
UI: About Event

### ISSUE THREAD

**Issue by DineshKumarVasudevan** [mrc-india-csr/katha-utsav-2021-fe#5]
As an Event Manager
I want to display the details about the event in the website
so that the registrants can get an idea about what to expect in the competition.

**Acceptance Criteria:**
Given an individual opens the Katha Utsav website
When he/she clicks on the 'About Event' tab
Then display the corresponding section with all the details present in the UX design.

Reference: https://www.figma.com/proto/A3B6c6710hpLvDUNvDrJcc/Katha-Utsav?page-id=0%3A1&node-id=223%3A327&viewport=241%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=1%3A2

Dev Comp: 8/27

**Comment by Magichida** [comment]
1.There should be a space in About Katha 21, Instead of Katha21
2. Content should be right hand side of the Grey image, instead of next line.
[UI_Process.docx](https://github.com/mrc-india-csr/katha-utsav-2021-fe/files/7098351/UI_Process.docx)

**Comment by Magichida** [comment]
Issue 1 and 2 are fixed

![image](https://user-images.githubusercontent.com/89193009/131984534-811fd65c-4221-41f8-b6fb-0c7beeb36f92.png)
![image](https://user-images.githubusercontent.com/89193009/131984615-97325454-4455-4141-88dd-63da85f96451.png)
