### ISSUE TITLE
UI: Why Katha?

### ISSUE THREAD

**Issue by DineshKumarVasudevan** [mrc-india-csr/katha-utsav-2021-fe#6]
As an Event Coordinator
I want to display details about the previous year competition
so that the people can get an idea about the event.

**Acceptance Criteria:**
Given an individual opens the Katha Utsav website
When he/she clicks on the 'Why Katha' tab
Then display 'Why you should be part of Katha Utsav ?'  section with all the details present in the UX design.

Reference: https://www.figma.com/proto/A3B6c6710hpLvDUNvDrJcc/Katha-Utsav?page-id=0%3A1&node-id=223%3A327&viewport=241%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=1%3A2

Dev Comp: 8/27

Merged with Master, will be pushed to QA - 08/31

**Comment by Magichida** [comment]
could you fix the font size as like as Firefox and chrome browsers

![image](https://user-images.githubusercontent.com/89193009/133216661-333f6472-7835-45e3-9c00-dfb11a56b39b.png)

Firefox
![image](https://user-images.githubusercontent.com/89193009/133216773-f9e767dc-0f8e-4d29-bdb4-f5210e393ab5.png)

**Comment by Magichida** [comment]
issue is fixed
Chrome
![image](https://user-images.githubusercontent.com/89193009/133409065-276848ea-647d-495f-aae0-6d3724cc74ea.png)
