### ISSUE TITLE
UI: Mentors

### ISSUE THREAD

**Issue by DineshKumarVasudevan** [mrc-india-csr/katha-utsav-2021-fe#7]
As an Event Coordinator
I want to display the details about the mentor in the website
so that people can get to see the individuals with whom the students would be interacting with.

**Acceptance Criteria:**
Given an individual opens the Katha Utsav website
When he/she clicks on the Mentors tab
Then the corresponding section should be displayed with all the details present in the UX.

Reference: https://www.figma.com/proto/A3B6c6710hpLvDUNvDrJcc/Katha-Utsav?page-id=0%3A1&node-id=223%3A327&viewport=241%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=1%3A2

Dev Comp: 8/27

**Comment by Magichida** [comment]
1.	For first image – Name Text is not displayed
2.	Do we need to display the Student ? ,School? Content also under mentors session lik above Figma 
[UI_ Mentors .docx](https://github.com/mrc-india-csr/katha-utsav-2021-fe/files/7098407/UI_.Mentors.docx)

**Comment by Magichida** [comment]
**Issue 1 is working fine**
![image](https://user-images.githubusercontent.com/89193009/131984959-df237695-ef66-429b-8012-cbdd2848dd6e.png)

**Comment by Magichida** [comment]
As discussed the below Question will be implemented in milestone 2
Do we need to display the Student ? ,School? Content also under mentors session lik above Figma
